services:
    base:
        image: mongo
        volumes: 
            - ../data:/data/db
            - .:/e-commerce-common
        ports: 
            - 27017:27017
        command:
            '--replSet rs0 --keyFile /data/db/keyfile --bind_ip base --dbpath /data/db'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        healthcheck:
            test: ["CMD", "bash", "-c", "/e-commerce-common/healthcheck.sh"]
    node:
        build: 
            context: .
            dockerfile: ./run.Dockerfile
        volumes:
            - ..:/app
        ports:
            - 3000:3000
        environment: 
            APP_DB_USER: ${APP_DB_USER}
            # the same as APP_PSSWD in the init service of init-db.docker-compose.yml
            APP_DB_PASS: ${APP_DB_PASS}
            APP_DB_NAME: ${APP_DB_NAME}
            NET_NAME: base
            SESSION_SECRETS: ${APP_SESSION_SECRETS}
        depends_on:
            base:
                condition: service_healthy