services:
    base:
        image: mongo
        volumes: 
            - ../data:/data/db
            - .:/e-commerce-common
        ports: 
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        command:
            '--replSet rs0 --keyFile /data/db/keyfile --bind_ip base --dbpath /data/db'
        healthcheck:
            test: ["CMD", "bash", "-c", "/e-commerce-common/healthcheck.sh"]

    init:
        build:
            context: .
            dockerfile: ./init-db.Dockerfile
        environment:
            # same as MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD env vars in base
            ADMIN_USER: ${MONGO_INITDB_ROOT_USERNAME}
            ADMIN_PSSWD: ${MONGO_INITDB_ROOT_PASSWORD}
            
            # credentials for the db user
            APP_USER: ${APP_DB_USER}
            APP_PSSWD: ${APP_DB_PASS}
            
            DB_NAME: ${APP_DB_NAME}
            NET_NAME: base
        depends_on:
            base: 
                condition: service_healthy